apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
  namespace: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      containers:
        - name: wallabag
          image: wallabag/wallabag:2.5.1
          ports:
            - containerPort: 80
          env:
            - name: SYMFONY__ENV__DATABASE_DRIVER
              value: "pdo_mysql"
            - name: SYMFONY__ENV__DATABASE_HOST
              value: "mariadb"
            - name: SYMFONY__ENV__DATABASE_PORT
              value: "3306"
            - name: SYMFONY__ENV__DATABASE_NAME
              value: "wallabag"
            - name: SYMFONY__ENV__DATABASE_USER
              value: "wallabag"
            - name: SYMFONY__ENV__DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-password
                  key: password
            - name: SYMFONY__ENV__DOMAIN_NAME
              value: "wallabag.512.ch"
            - name: SYMFONY__ENV__SERVER_NAME
              value: "🦙"
      #     volumeMounts:
      #     - name: wallabag-images
      #       mountPath: /var/www/wallabag/web/assets/images
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"
      # volumes:
      # - name: wallabag-images
      #   persistentVolumeClaim:
      #     claimName: wallabag-images
