apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.spec.domain }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: infrastructure
  source:
    repoURL: {{ .Values.spec.repo }}
    targetRevision: master
    path: apps
  destination:
    server: {{ .Values.spec.destination.server }}
  syncPolicy: {}