apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # not sure if required anymore, may interfer with cert-manager renewing certs
    #acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
  - host: argo.512.ch
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: argocd-server
            port:
              number: 443
  tls:
  - hosts:
    - argo.512.ch
    secretName: argocd-secret # do not change, this is provided by Argo CD
