apiVersion: v1
kind: LimitRange
metadata:
  name: limit
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 5m
      memory: 25Mi
    default:
      # peak usage of the application controller may be very high
      cpu: 100m
      memory: 250Mi
