apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Applications"
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: '*'
  sourceRepos:
    - 'https://github.com/tillmzw/argocd.git'
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
    ignore:
      - kind: 'Secret'