apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scale-argocd
  namespace: argocd
rules:
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["list", "update"]