apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miniflux-ingress
  namespace: miniflux
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - news.512.ch
      secretName: miniflux-tls
  rules:
    - host: news.512.ch
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: miniflux
                port:
                  number: 80
