apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: miniflux
spec:
  encryptedData:
    password: AgCLmwA39nBwUh6bieGZP3sIlbm5dy3HchtL+czMjXmcsDD1A6W8Z6tBF04AI9VbylXuCg/NhXnTdyRxJiPMgOZ+1fBsNX86Y5a1ZdRd/YYPfPQUvcQC8SfhN8BIR7P+6oh9XvaUTFCsnWrObOkwJvROlA/gRX6tK67E68e7mqLlvcaWSi+gOfaWBcW5LkCFRHx2nJ33wqnC4jAcPgsqzuwpOkTwykjVZCoudUngL6A0jy81P/7tjiqFF21lBRni6MVTW2kMxViMY/vJo0mZFiPXBixykwCZGgUQn5gGKp7yXBEsSBSy1sjx6yLo+iQWD9jz/mobXVWFcXVJkRZLKGbYbA5KSmF1oCR7MhF5NcfWkWLSWeLg37uhsLn1lkp9rhebtkFPUluCOcxQ4aWaI9FKCFWljYRF/JJorSdqBIGLC40QaEq4xs1GH5bJ0r0BQcCD9Ok1KUgaanNI9+NyDDPrJW1MhS5BFPqXE29lHZMoUDFBtaDDkHcdSO/36/80BR8EaEdX39p+xT/3kzkALqtojrzcLj5aoxGi5h8MADNiIklFn57qrPp7s69XftMRmVtxZsWQ3b4ku+hSsR5qLjTaT82nJnav8ea528376e+XSuFeJOBBLoQjo4TkSZ3gvxJTwV5a7Uusir17H5raBrXg9mv1nN8ofjg7tZm6snYhrIO0a8edWJVYNTr4NyExeRheZh/krQ0TYY7CkrWjxzqe5rTLjWlrAVQQJNCgQ8+LVeF0hUFfelz0aorUyfo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-password
      namespace: miniflux
    type: Opaque

