apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: miniflux
spec:
  encryptedData:
    password: AgBo2tRw0YKDI6IU/gSrQvC3bb+eDgeh+nkVEUZHEUEXx2cPbiEK9RRPp7h684GSTCSHjYF40tllyfiPl0N0fo4kysqEZfpgnpc/jsbZsFQIghyEqjuXBCwZM2soBxFnoHvZ6gyuSLGdFVx6Sp4iNSdR17o7u/xh2IeBGuBQZqPCyunWfh/W0h7OEhDr3dzlbGUYAsllcex5Jy4Pewou6wfuhOC/YzCxlqGtc5rAR8OsbuIKn2WBI4Wq1ZGEb5atuqO38PzyRQ1pniq+gzG8xS60DYAjq3FXUlhM4jI286VRj5lZSlGjkAIdoboxYCocRl48HdkxCRzIuyABK5Md9mbtzKdgDKbOXFy4kbcc1vf/6QveEJIEFXa2GW8fYZBqreQG1MGpivmml+SnduUpLxLvSPa376CCGwFKuqCpHuWDlhrVXGrDWYUDU27S1uEDLGRksKdcKfqPgdDe4jHzoOAS08U+A+JQM3r/Gc9WIUxcWCgZNNp2pThZi05FG1Hco9jWS3AKOFbu9745NjNJpkCltDg2q7zuQhEuIJWedM7VY9H3tCVfouqi+E+ofBrsEqUAy5xAiAR5kCKVCsXc6AyRSt1Xe+hNci6yZQn2zbmy6Rwe6zGTXlh9ho1tVUrbFGugTehtFDY8TixkHEqGWUCjyc5uQ5B5hwHNkGBc+opTkRUSW7lOX2QJINbvRFUqrOASCT7rgIVkjA8F1B+KdizyBZYITFY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-password
      namespace: miniflux
    type: Opaque

