apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: miniflux-password
  namespace: miniflux
spec:
  encryptedData:
    password: AgCPa43XU1R4LuIYkhTDEgW5gkchcmTB3Z9GYjg0+G8VuC6R+XF6yBuKA7OspVuCwDy6Co9eis1/ADCL0zqn4l4sVProR7P1gEqUge8EEiyuA5JihSn6kO9Vy2369u9Dwzsswqs8YUTlDNNg6Z5yFcXO2pjwQyyFe2gmuFl30sziU4iL6TbWoXJYuw5yNa4ix/4LJpr7X59GrDUSGaXS4dlfBVvXiVtkDkqr72Ict0r8qyX7gE7c4AE8xaM9qgfCCor8tEtZufZDvuffnJmzLo/z7qVPCJfVAciikv+ZFlkNWnvVggK6eBF7zw/yD+Z4I9IoIsTVpneUqj0qZMWSP9xe3o4/8T0XhV7siKPWbCrWqEJkQRlzAN2EOQjYB1YRRV/F0w0rJaPxHQbqNN/3zKXBFAkiBIeZN2+mIwDzL4oJPQB2p/vP8QVhx/0iMSRLxihYk07VNuwED411/JZysvIHVDSiz39nPaNaUTkuKteXhAiG3fYHrE+UPubfLtmsX9G1TZkYBE24tb0Q9bkjakh/Vhkn3TSBg8aap+38hZC+6JdHeIfFNorMJ4b5Trr13UJbHkKpSKLM5piMSstUw/Vz5Np0NXdGBu8fyOHjNYRgRm+oWDnePP/IkYsX4Hg4BpZ3ipP8X7nU0GXZoOBqj66uhcSsxOFLcWCUbcLvb6JJA3fZ8ugJqdAk3vdLaBFzLakMcKncb8L0ZT8tjYJL2/YxEWlNRWU=
    username: AgCxKbKdwpJFjmXlcv5XbJoJKYTqaMM+JDJMxbkTzogpH2xedw9HcT6UtEFfDYetphaZlUZZp0UjQDCwLk3QfsDnT0PjhMxDiGNIqfgDGbQHs9BAP+VExoyNvMRTPnj3vE7VeXrMgZMMra1deAZ3xhjk2Fde/dVvW4EQP58e6+RqikyfT1z+MzIV18obBsaVwy2iW5O5Y1gj32tQzZwAFznhC3p0IWDBwPkaitxJC8M27EfYNYPw9Ur4AaJlK5fv3FbqYAwXnJNaqaghI64KmUUmh6GW2FyuMBLOisFz81GPpCrxlx4EqO3mDP7u+z4VyL0MuBV75/w0+nPsEYpYAhYOuub7f5zp8SFjbL8++WivPxQ9eLAfnkQBpzTzN0a7wIgewS8DFxZpZ9B94eFK9nn8gG2cBjx6dLvKqN37qt1INm0n2e2QZ87+U2I3HB9a9CzXBPB2fLLS7Fqg+2Ef5Di/uGQUC3D6OWdUukWXFyDU53hpNRw4x/FT/ZcozRKgV61MZPlU8J4mPNCl8WZX+p1orf0WZmwzuMmSX0DY73KWRZ0+RXcHWc+9Jie8N2xMvfLbKknUI/hpTApZi61g9jsp6q1doTgcwKLYhDKbNvO5Kaa+NYCuyW7ZTY/p8T4liKxIHD1jKdwez9vkHOkfrW5MtfrSn+dtx4yV/wqlrt5gmiO3Q9iTpgLM5WKakBbeEEogHH0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: miniflux-password
      namespace: miniflux
    type: Opaque

