cert_issuer: letsencrypt-stage
domain: miniflux
miniflux:
  resources:
    limits:
      memory: "100Mi"
      cpu: "20m"
database:
  storage:
    className: default
    size: 500Mi
  resources:
    limits:
      memory: 200Mi
      cpu: 25m