---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: miniflux
spec:
  encryptedData:
    password: AgAX5QXpbCuEss/brRifq7E4kZ34oGrzSa6CUSPOf9Zd9GAf1rO7O9BcthaeFrOYetY7md8L8sVus000KmCUzhQkAlHGufMYCGdSAFFwuKxQ21V1zU6PGeVnSzYA9o/k0gCB5wRXqhWxA9fFRrJonlpSVvL1WpO/7QocalPmcMNvbzhg8kH7COniJ0MgavQL3pgQkJ8skTl6N0A+kz/OOVL6Kp9Dqu1j07txOvmDdNfhUwzdB5cATCbQ5ewBDRmEzrAMJWlHSUxjQl03ZclQT1xO/uApOTfKjdBoCjZqFOo5uJw9dOqRayWECXbsIBmgccGfAZWfdpMZUT0ExaeZrgUI3kVLRGyPn/zqSZzaWOx921warHFUp0mBEuobRjiGK0b325Bf4YZZfM5ES0UssuQAkLMKEGDB8x5rhmDWJ8/D7uTXdrAN6N5AZ50sncjmKXpZe/tQiKCdxFQTZAOVZDLWPkcQ05k37SboYydPDMndcRfq3/esP1xn9XiiAlmZgh2xR2nGL79YnDFUTI9gvmLuLRA+tZMxuI+5q7FAEp/qMc7D5ZVgW8EfaGeoStZQB4FqdJy+Iumuuoggzlwyhtkr5/jigesH+lqOJ/cwwhBFa9pWf9Xm1tew2W+wRyrKsDjW2Wt+qtH7nY5mwu0Co7Lzul5yp1cAMztv89kK20xlful2CaDUYkcMt9bJhIbvyXUzIQDq/mCz
  template:
    metadata:
      creationTimestamp: null
      name: postgres-password
      namespace: miniflux
