---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: miniflux
spec:
  encryptedData:
    password: AgCtvcFIJxeHq86L4Xtf1dYvRhuiycnipxZMVYDLUS0QxhxB0UqXk0dguq7acOTK0nztr8RximsVHjX8kiNJfV+ga/kjs1asfdF1k24++ZTQn8Nh+lu4k28Tz9g5ceBl3uyDg8meyCg+TIAwAuf4ALjbABMuUEQUS4H4chqzRDp8Vz0n+I2fxvv9ozh5Vv7+/IY633DaLvBwkFz+D1l+sl1vqDS5PcjWiX4HlrAYtNa5VdeRx3Xp1rO0UFAGUihFeQ2eTNynltUX3Mzp68YtFkY4ZD93uwiTRnvH/M4zZRvi0sB8aSrLddKNAxdR3D7JeX4gJAxng3J2DmYgVCPFbej5TWp5O/q4nm5iVTN6jx8An3E3MmsCzkHjq7VRh2hJo17fLaICpX1iMAeP2Nqbq9uP9FChF0D3bgFE5ECBBVdnzYxo3WMDWKULC49oCYHVdIaSTHxfRhTP5Q0Jis55VCu3PRJwSM6q1ijVgD577uxbHTfq8tyVPUm0W4d25iX+AeyjPXQmnrJa3k4NlJJG8MORcH196dz4raVafc4+coPlNt/REzmbv5QvE2PXrfAYF62pqRV/3fM9CWpK+tmt53vUIqG7ujY1QSJKiyyKmz0bucBgPU4g7hmJLoQm9Zc8o8s7A0hcZwwA2zTY1ebrOarHe4/0oIvXKYjcX2F2n7/oat5cAy97L8HrytIpV7fBblQ9DKMtzvkV
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: miniflux
