apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
spec:
  encryptedData:
    password: AgBz3vnWuSvYiFBdlefcJVTqqpbHNWP0wcGdLWzxkBa8SRvf0riluftePbhZLk8ANxeJMioZmPykV9/grzb8TnofQcbU8ZufGDLmDlVLc841BM9m9XHU3h/4iQpUhOPdmxSENfaGBfW4X6YewJYB0pRR1GRKptfn4bDS4UU3JXuKxAsI9oNAgMNuQ011YRvQqff3ZdWagWwjCrUv/QjyIm7XMQIQjmWSPOsngqlr6A1KrfgoJ+LUAEFqKaKsyPRHeUK9ZsP0S48Mp9zTJkbhQpNj9I8jiYBHZ48dgjB3D6wXw3LGHfDn8fJ+t0aTwH3caxaOFyYU9VOntuCicfQL6nvoWuQzuVsRHwOYeyMxiuZTV18c+ZVmwKlBgvKXgY7vmmt+SVScMK7jDCwz+/jzXK7z+n/idCIHrmCJHVVWFixptM3ulszGPPrOQmrWuGq0DseWf6Ir0mxGoUlu3rOKOxCj6Ny9tAWTMi2mUuXy5LvDgMUJ7Fbxgf/LdNv/08ZvNbjrUWHGL3t+Mo8AB5wgsegb1jBJEmBaiIbnaLXP8Uiqea7BTbUjFGp1GJYrCbXV/kPR6N2Rozqohaw6VRXP3SveEycQcP3gtGXkkKXrgd78sFFYOT6vllWr8VzFxoF/oOBQi+yypMiPt9dSeoe4jLSvs5ini7oJuTIPAhVMJtk4MsamaVYYlEGvX5VZoxagwHRvF6d81ZhBWm4jfg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-password
    type: Opaque
