apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: miniflux
spec:
  encryptedData:
    password: AgAx5ZsoexFWgXk4hxOKYSFAKgZ5lE7dPgbqheZpKbt58SrTO7Agb4WBqf+YaJ+gOUxm7kKxQC9aIQVvWbDDgGqoZOiRTIfLZOFx7paars0lQgVmx01fqnP4y2b0F01mptbMW6TW6kGyP0p7SJ2W9F97tIjYyfihDLmiXZ4jPfpa52eQSQby0ZPEdL1yjqUDxsj/wfv54tRcWsqpuS/6+iZucPE5TcOm5OcKeVyBzkBzk6FRnXcsfeTFd45WLk8xIWgQBlienNYGt9yLPvZxa06aFqw6EVoJSJbuVhizUD8U+SlvkU8wkBN8p6AvOYxAW0UyR+LhXR9SS97SGVIs0BnZM6hiVIpno2mnbIAjcYyOipVdv+yuXgV6Qp36cjkLeIeLJQDX0ERM1o+atyBq7CYGDnhlajtbgDGGn/weEu2z4lprQLlbuS3cF2MUTEUYncEGtdpVWI2U9dM2YytIvhaiJdxBTSd9I+iQ1z9K6yQPLnCZ54E4gheyO6SP/5hDq870rvANj1mGqDuZ5zvToDkrpkvNCo3P1wsahKWndRu2M8ztFqq1RHmObMCU4I5Ef1yIna2rCQzrrClFFI9SIAbl/2UpP3KwMe1r9FMWA3YF7qkelQtYWLHXyISl/DE72jY6gnvY2vt3IVQrRiq5cQzz35dW9P86+7BkgisvF54xjVkwdCRMiZuUhK70wz7qXaWmKW/dXHR4A1TO3YRIKiVDI1h2pg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-password
      namespace: miniflux
    type: Opaque

