---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: default
spec:
  encryptedData:
    password: AgAMxbFvjMZIs/wdpoYaZGHsrk6psfGM3bJzmQwHf0GCtlFN5R5BBpplNEysVnT4GJYL5S3zwId+tuH0ttcfwbNAD508NOC3hlYRaUPF9P8/OBBaUU/0N+U2pvkihp509xlwMArIcd2U5wIxlitXnsvDKzlZHx+9BU24s06XxC4Vr3t5TW1XISOOmnpNeVImZPwgPNQhUIdpZ2/ZFVB40GCFV+vHfRBLkhUlZwUo38R3SiLIpOwHnJHn5nfR/I+QXzFBAVXwKZ128TjIFvGwnHZUCeKb4f27bgiL3bL9x6wK+DHGh2MsgxAQRoxpxNRvshdKqJzPva7p5uSC2iIkCYvI6Pm4Igywv1Gr53EhPuEOp0reNSFMOQx9yzotijIqNA8UbP3Mz4Jh9UFPkY1dFhQHCl8/lzx82rVJdU8BihINsnFI5tJoX20OjL8BeU7a0Np9hsq0njWowZPImNg1DidAIPRfsSJ5G9iY4T6vhuiHytjZhRdJoZIvSuPMYu0w2uxBMFw5UMj5W5LkdOe1L2UnGJzhZH1YeocXxZ6Muhvoq1QdLS2RD/tIwCc8O43eqKWLkd15qgDU4sfekiqpVV7RPW4dcTYRPvzM3LyAOZ3WGncyG+oI7lPJqgtu8QO0vaYf3WFphvWMICaQOoHUHqgnDTvIIsBtB8MtlfiIyzCZOdtBb1GJYnJz1h+5Y2cLnS82uT4YBrEm
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: default
