apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: miniflux-password
spec:
  encryptedData:
    password: AgB8keBN8ZnNlQzbaJRcadwBczU/yZYDq2lLovmcUiocoGAhL7CKM5Dvi1KrwhoJ/eYcM+Asg80Uv+Fo+tqLo+7PAD+AoBduue82m9KenF3YxL49ICSUkfvy4WYzWOS9aPyBdgq2hOm5rhYOz/nJ9OgEYprU35iYZO/5HEUIBr1bTCtdtityPRAodaoB3syZhs8CQGRU/8a8DplBP5AiYrH+nuHfrHzg8Atnq9oKfceAWeVi/LC3r0sQxLYdU+EQGJzEr1ywjzXf/sBKV/nYRJ5jBiV+DFFVjwWCdjQ8EM6vQooWV0QUzA4/+IiIGWW+VuGH0RSDeDzVDWyH/bQMRhLB1+gV+YotlbYbtIyben1M46yyLFWjm21pvUtS2mYt2dw4zhuyoynK8Cq8VNzzkJwMlMZW+SS7bfZrRvOleSDCalIT7C7Wy0IL3WeHhY7BEdcGZZTr7RUHJC7ZUQuDBxiNQBTnw+u4EsnArlKxECW3XbKp2Cf0+W4FZ0eKDmb4y21t9EsPqHgsA5TjHEoWqo+LXtxsIo2GlKAJraxAZqHS9Ige7vi2OkhvmiNniGabwUiE6ka53LcW+FLH6jigCHRmBSPKf5Nc4p9dIcNGWKlOTCEcw3x+aQGrAHh+zhnODdWU0TdQFokUMZIF6MbD+t8yWibrJhLh9vay9sTZyyqsN6VIhL1oOZ0BkqUuMnP1lUcsruyJAJYfOh1n4TaSYcjr
    username: AgAtUlwxjEfUfJ+z3N8E7ffZl2EiLqaSlCzk519InnBlsf2CFsWtS9wuH25yiOhRfDdguwsLk3doNBtgniW7XZeAmXNK34yrYeBCtQ2/p+CMx8CkCbuOgPItUe8nLquMZIENIYnhPehRI502Q/uzLocFclD/ga06FwIyDUOzDNu0gCdLZpKn5H/i15ad7Ytd6qThkBP61JSOggEfch6FPucDXlc7nbCBOFSjI5QeX1xrfVOfyuf21DuE9Jy2KqPmKBP2C9MrOXI6qyJSPm8xNhb4xDI/0+9+txfJmQhllWdfHd5fw0bhOezF6udq+RrA1wwF/pxzgbCjvzp1u+VssnxxoxjopL+HgxMc8iYGqJXG6eXczcClMe7hN7TdrjR3tsyF57ZY8t5J8AX9UMKVyUngziNzQ4EERjJH1fCyB8h8i+XUb+/MOoZZpkQ0gmpgEO1zZfdHjYUe2C+iFGaVVm8KZmffZWZQKkudrNZEUPBglWQzS9qldUVjReSnnpGhMNv2tpUcHO54NyC1VZP7ifwz2xWpUsGFe1wYRXSBPWQE534pQz/ETTpQ2teB6FyEm4Y/3MdBrI0KDs1uAiuR8UM8Q3Phosz995Cik/IC8428pyzMVj28/misga6a9cxC74YA+eEuf5y7VALXV5lDLuiWfJPbHcSOTbLxlD4vy/YQHmGOQV9YS/+wh33iZ1PJ2oD2nalH
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: miniflux-password
    type: Opaque

