---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: miniflux-password
  namespace: miniflux
spec:
  encryptedData:
    password: AgC/pFRMgQMTa3BegtlmFtElC0EwcaOG1OCnnLBMUZ8dx1B0Zf+n88CQTXLsjdCkYTBm5N3tDfH1IF5yqzHMxGhy8l70hAl5AKx/XN1sjqEz0eGxCdtY/DqeVGO286oSvF2lg56gjKCa4heUb6+sqsCwgcBMI79agwjjmH/kk4A//7f3TDEdV2Kcz6NvrgeKQquDnaJdUH8n4QS4VuCtxp/f29d6pcSGwla2z4TgfnsR+ATsJ3BktBxFduzpqcG0hZxw/+KrjhgiweA8hbFUJB0lYKuSPGVyilYXB8y2ueLFizPVJwRqs73cZg5Q13uvhGgWP21xsW+S8fdCwTJ4CSrCKSZlbC+/ucOw/QuNdlvCdnnLdFJD2bfWE64ee1zNUacNSl8gRjVKY4GXEMlm6fYAyCEB+pwIUshsRMAjmiNFNNOk4NuieujFPEBBV2Lt88aoPsHlwH6wYPtg1a+S228X6YUnIV9qgSDPt9+JPNf01wVlmrX7zcEsiGc63UwU0ft2+VulBmlu9AHZFB2ujf07j7CPz2YBjvttPfb0z8O2NMAOTeYHXkiWRCVRZfibS3TcFsRt1TnulVVM39w8PvZ0GChVABQhNPTaDfMN50LwZhmBVMzNw+qBExXmMoZ5slUyi0qGy6abS956QLwb5/5wrghN3XhAaCTqGSl367DaDIMG5JRHHG+/AGmn6z2t9whZXaidcvpg/xdfDvRndgNQ
    username: AgBBWJgsy6PlP+712EnlGqpvajl6UR+M+8PhQnWOeUvCYhgTpughMuotOqpIWZoqGAcNBL5hdT6dOPX6i1q65Xz5uZ7nJTTK0obYuGvJngpvGLPlSqQDWuZn0WbY+CeAyrscCARI/31a4n1KsI4oYe8XZnw7/Tz/xrN4ovIOV46fomzVgvi3xuZJ5NOaazF8yY8J20mYmw/R1sniUXx9Olw/sGhTFpn7HGDVcQDXgIcXafQcNFj0Hnvd73eGGUFS8e9XMlhGp3HWbKfaBYIO7BBTXNwgCLF0R+MVNF4/B8oevT2nhJm+gzpzTdoRSpQ+wFbood7NnyjMe2MRgysQIb9zAZYp1/qoUzr7zWy6MCcTtKhC4YTyflg59V+cqyakxGN2FJRH+Ymhf2Gxf8UzB5s2QNHpRAwZabnb85yxPNdP+Zzo9UM3FxxkBInpRc0NNEuDv4dumiF8FsFDZKmf7+ygwLG7HgnXGf6pX1q3ZL0FioqSbA6liIAT885cCQhRMix2G5akG5N3gNrDyF9MmiWwoO0bF2UzyFwPcJIVpmg+6XniPeFqbGpQLiQwwqDQUaYXWMAKMYo/MUMp9CZzx/dBK8UE8+g4yMmRR0naqyfhCxKIT7+Bh/XxenzU7zD2kVXclUCv8RISHG988DOWlYslBZUbIzSIRM0Ssw/cbuoXn8RUwn72S9i5PtP8qGMZX5AsGkPW
  template:
    metadata:
      creationTimestamp: null
      name: miniflux-password
      namespace: miniflux
