---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: default
spec:
  encryptedData:
    password: AgC/ihBqqLnhVdxuca37obPV7wEgpyBYJCJryH7sg61MfPyuiY4UvhmSkUvp1rCYGxPUl7lGo7PwYR5BJzDuOgDp4Kjs4yeIOKSwfdehND+7VlF36Rls3ATSbShjl2i5pm9lThR7aQhTmbkLZgSZM5YDWNCl8NyGUKtzqfaa3b4JgJnc4ieIYYuYNHeaOh/zBKTVdEIp5yCIzRv4WToKOgNoKUWBor+hzbLFeOxd/V1ibsw31zR4Isf64JeLcoYz3ASBbEECkv61LdAjCyLWAdE6mkB/JmWQKP61JUUDyD1W+evYQzWnAsoq1uXT2mydgH+vnps5QbxqbPpduCxKIoFwvQv7DxtbXYnRAihHXQ38IMeIjLZreyVE3YEOKIkJbbjnLhvdRX66ckCPGMxyZh8Pk8DeAKtgEiR5agY5Jzc+xzCsmVJza1G3JkH++hktuYdXGdkqEte/zF5pCMk7R3G0hQoZ/VadzJbnqYJuO+YNLpaGUhUefR9ca//FsqWx5FUR/OKGh6Dlnp5IU6zy8A1s+zRJQpJaIlgj9vKFLu6PnvTUd3mOQ26CoED/7uzscKNXSCBRaeyMk8iKy4GoPDcW6cUfaclwavT1Uchdic17eSTucwYNbBw+33Qgh6gqrWv4niVlXGeHU4MHWGliT3Ku9PFdpsj/v032RcKapUC+S44ipawvfMgWCr377N4Bpovn44L+s+Jy/hKSWragskOc
    username: AgCGdkHzgxsbmWMS0hxmTqsmeIUALX9J6Nz+GaaWB+53sjMB6lF2WybRpwFz+6ZK9+L81foqPVQlrkVvOrkBV0IZ6pFbL+LcnyrehXxEN0vc/hZvAoi/Z1ELt4TFjFPF++VkjvpJ4wdXiQsrBitsZRQLnxBtEFwUIjlfjypUSkPCSdimaOxedN0o8Ojxe55I2S2Zbbpds2bT1zXxh0bum5QdUkymyeDWWfJGOX9GFhJ+qrowt+REARhMp6nSLATjssyuQ7ZBlca+7tfi/73iEczzYZCRvWZLMw1/KSAW+0bxLarGXjH084XtEFw3Wz2gVjvBJOEln9TWRrtsRjr97YRRZell7zVM+lOGN22lWjG7sEyjvUiqtkQT1AAK6/8qtOkzqITwasDdGAEVdHDs0UZ3vhW5yczb5oERndY41bB4ePbf9kyoij8a7ZzEWAbodTIm9qOT3QODiMAUD8fQZwhTfaEZF+/pjx9wjxNz0l9MiyDgtFYedXOD8XSUbSPeOqyRUVBIdbY6y+D+hg+rFTxhLvcdip7HR8mhPH3nRNSr+ET5q5M8MFdamWkN8je5JCjlRsoZVAJyJdhAvnkE5LZlA9tssJOer6ggoQ+foN7H//2hMxdV8Z9h/wVi9FDBcxPqfmzNZmxKAmuBsjSF5DyM9giD59YTEBuM8idpXhE7brzfpCuUaN2LvnU+5iocPPLaUj+h
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: default
