apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: infrastructure
  source:
    repoURL: {{ .Values.spec.repo }}
    targetRevision: devoops
    path: argocd
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: {{ .Values.spec.destination.server }} 
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
