apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: applications
  source:
    repoURL: {{ .Values.spec.repo }}
    targetRevision: master
    path: ghost
    helm:
      values: |
        ghost:
          replicas: 1
          ingress:
            domain: www.wir-feiern-mit-eu.ch
            cert_issuer: letsencrypt-prod
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ghost
  syncPolicy:
    #automated: {}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
