apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: applications
  source:
    repoURL: {{ .Values.spec.repo }}
    targetRevision: master
    path: ghost
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ghost
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
