apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.repo }}
    targetRevision: HEAD
    path: hello
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hello-ingress-route 
  namespace: hello 
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`hello.{{ .Values.spec.domain }}`)
    kind: Rule
    services:
    - name: hello
      port: 80
      #targetPort: 80
