apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: {{ .Values.spec.repo }}
    targetRevision: HEAD
    path: hello
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
