apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: 'https://helm.linkerd.io/stable'
    targetRevision: 2.11.4
    chart: linkerd2
    helm:
      parameters:
      - name: identityTrustAnchorsPEM
        value: |
          -----BEGIN CERTIFICATE-----
          MIIBjTCCATSgAwIBAgIRAI4/1+bq6u5b7sjB2JjYDT4wCgYIKoZIzj0EAwIwJTEj
          MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjIwNzE0MTUz
          MDQzWhcNMjcwNzEzMTUzMDQzWjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
          c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABN4a0uN/8BTe5r1c
          HtGZGPCS+UGhCpb7UEvA/9V6lyvHjnrdAgSC70wII5TYEN785mNvvPPxBsGfvgjn
          rePlTmCjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
          A1UdDgQWBBSlRjgZ4mVIV5h77OW63sBcGLzSWjAKBggqhkjOPQQDAgNHADBEAiAU
          1ba29xaYZwcM3uRQjai+KGL4pboFVHu3KReJra2OlAIgOUsFjCtTH62wU24ixoHq
          6/uRteI61EXWqQ4g0IecCX0=
          -----END CERTIFICATE-----       
  destination:
    server: {{ .Values.spec.destination.server }} 
    namespace: linkerd
  syncPolicy:
    automated:
      selfHeal: false 
    syncOptions:
      - CreateNamespace=true
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  encryptedData:
    tls.crt: AgBVMeZv0xs2BxSwvahrkdxbFhT1hHjBGIS6di84GidE/UPNaEypELzzY7xiMiiLc985RPpmV4R14Y0nFHFT5c9M5mUK7hdXsQnk/KIDPr01BroYH5g3T6+AzN9c8kQmD+82t0EGOX6fGQLw1qHfmW1LcH7qtHOaGRFGjp7OOcyoxH8rOZVqEh/D/pQORLs4fkfusu87bpUhpTKeKF0okL5Su96xQP1P5LfHYkNbFmmeUeTyW20jbIkBP+ce9UNK6pzYSFjhCiiYRkfbtEe3HL7Ap4OPxrHgrk6ITCiHAoLYy4eHxqxfzsYDDO6SsBia5DW/LyKwCMNHmNclX4LBMNaQxLL8b8Kkuj5ocnG5JRsyzPDB9RjeD+5er5n/LSCdcqxaHRjAstFKxVNwSuGU2rs2pHYRVj2+sv6tTW7PHAqhFtKV9bunP6B4Z3C6DYMbnK2t5bMXstQTgETV5kgQob0kHMaz1vELvANRqpSbQROBSNsIdtqwYU5eJMi8Hp02YRIpm9mE/25XPTFIk8R7qNi+ahieDgUP0cFYrpNrIosfzxsizloYFfHunsBKDjz5VQMBtGrHi5yajTWqOLH50R32cLWUnOELSqFb3HUnDuNpBNQDjf2UU0DlNrq9mMwzFskQ5FEBXyjtf9ulrulClGb5eRaBDLtYIAoc8Ro40cN7kdKhG3gYzRnHEJlXqztUDJPOuOXxPCMDcac5jWzBQn3xutLTMJQ8RdMjY5Iav33nEE3CrIHLzvEXEDso02TA1tqtgJtB7PYtO0+Ad6Y9APgruaDmqNDnDUJmvUysZCu/UrrHkYGjVsrPoOY0o0BygWiMNYa1SIHBMyV1MQy0TKU0yfbuACC5iskA/55N4Y0+0I/DcNSwA4du1oAcpzUhcTuo9Y+gnsLfP5bhbTMAeBm24R5OaG9ZFcHfMcL4/5U5zDt8KW/iBYfGMzhOZzxv7mRGIGdC6lv2bQ5pZrsnB8ksc5lixz4GrbYjI2vG8IpBmn5CtPX0AHjygqRmNVMZ1IBVl4Q/+fD/PZc8dWXzma5jVQh0QqWYdBfL1A1UkPRtBM2eEgp7+j4VsrcfP6QvTxLUphMBSOstG8K3fk4XGDPuNYsd3kAEWoXHra4Guwt+LeYBNQUbC443YDLyEzJngwJS6n2TR+8dXhF1O+V2KlYuu8PX5F1GA5UQZGoGCjykBULZG6UHg/8infrges33ihCW+14ATYH2zn4YVAiqQr/Onb0nQ+5zZXLxqdGb5cvDEpWhu13H4NINg7FAzalX2ZHdmcEU3+fAA7REnzSakOy5b1JYGxpI0Q7wTPKkWr02KN5Ql1vNJXyws/ee8iEEBqy8xtSeTeH/2s8nQuKGLCoeIgpukYf6BGrj7nX9FwOJE9MUSk85SCu6LYin9CF0q9Gvz6ZTvowYEN9CtzXy6fbVXM4P2vGutZN73OlOEvJ1TkeXljOcdt+040FaWZTjkUPDooiH9VNc11fuOAhZPYzPWbCOTIzAKA==
    tls.key: AgAaIPwkUIWAA6YYCVtNpOlDH+wI3/ofB+xh9r0znToa+kKHRi17JrdI0FSNmw1TqskhM5d6a332AGVJeCBQNMzBjxB3hjyoWin5g99SD2b14NAiL6z3BbgZwTP5gA2BJyCFbAdyOuY1GUbGVk3GclDJld0lZHiilTcxW9VKYyF7mKMRF4d7ssrk78amRbMiftl7nLwZTNZLeQJfodXY5pqyPKdczBrGCDDWQ9oZ0ITuKXs7noF/eLJO1t4R2URRzM4iiPEkGYi2o5hqz/oLPYXQs0+YT/z1IGcXIEtW6/NZn4SBXT9k9//FFTJuTvcpcjNZnCYyVnTGdCzM1hKBAD7e7izmfmwPdzHV88eYp3bou71gFcL27Gti96yozCAG82JSjdP1L7zVJvdMoy/zrxBt67Yx46ccEMADi0bljFNXeCQN2U1IeZLC02CgN2GEw9svoJ4XEieQAqN/+tlF9JxOMKN2+yqGF8POz+uIiAC2s/HUrtGTwFqL/50oCL0dUpNkHEgGuvyOscys7iY3zdp63AowamBX7RWiR/KcQL0xU9sWBY1k89UD5QLWfWKyBGxsvF/rfG4VDfsnI5uABPanfe7X0Ro6dX4fVNeFZXcYudfhsQKmgW66KGcnmm8aO7apK2YeofDMkZLcn282bTST1n91ll7wlU2+oR7/Oc6JH2ZK46sEbIzicG3Sa7uv4+Fd7KgbgRHmVSxutDrKaehft3r1lEelAXfTOgTB0ljcOqIV5KGeFLaLHvVDWxFev5od3/M7YDoVedGwFjo8Yl1Xp4w4aS9zAo4KdUltiMKqSrECHjrNeIT3jKWzciZG7R5p7lzMvnKLZCK8M3rsT+ryCMnWsJGXge9b4ypdS314lQW0OeH0KyvFu2XJ6FpN+udQoykkZhVS0jVSsqpxuQcyrJwJs9NVDWY+W47p2jZ9DEUFh30bAYzVDp5WWyWONCrO0VV9p/KuKcGdhl8q2AGhxbdD1ViuQb1bF7es1MkdjSUTxg==
  template:
    data: null
    metadata:
      annotations:
        linkerd.io/created-by: linkerd/cli stable-2.8.1
        linkerd.io/identity-issuer-expiry: "2021-07-19T20:51:01Z"
      creationTimestamp: null
      labels:
        linkerd.io/control-plane-component: identity
        linkerd.io/control-plane-ns: linkerd
      name: linkerd-trust-anchor
      namespace: linkerd
    type: kubernetes.io/tls
