apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default 
  source:
    repoURL: {{ .Values.spec.repo }}
    targetRevision: HEAD
    path: longhorn
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: infrastructure
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
