apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: applications
  source:
    repoURL: {{ .Values.spec.repo }}
    targetRevision: master
    path: miniflux
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: miniflux
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true