apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: infrastructure
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.1.4
    chart: ingress-nginx
  destination:
    server: {{ .Values.spec.destination.server }} 
    namespace: ingress-nginx 
  syncPolicy:
    automated:
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true
