apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: infrastructure
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.1.4
    chart: ingress-nginx
    helm: 
      values: |
        controller:
          config:
            http-snippet: "proxy_cache_path /tmp/nginx-cache-ghost levels=1:2 keys_zone=ghost:2m use_temp_path=off max_size=1g inactive=24h;"
            custom-http-errors: "404,500,503"
        defaultBackend:
          enabled: true
          image:
            registry: registry.hub.docker.com
            image: kenmoini/custom-nginx-ingress-errors
            tag: latest
            digest: sha256:a25d945abfcede571408e78781f86c1e3aadada5d5fb4815354496bf39daac0f
  destination:
    server: {{ .Values.spec.destination.server }} 
    namespace: infrastructure
  syncPolicy:
    automated:
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true