apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 0.13.2
    chart: ingress-nginx
  destination:
    server: {{ .Values.spec.destination.server }} 
    namespace: ingress-nginx 
  syncPolicy:
    automated:
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true
