apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.1.4
    chart: ingress-nginx
    helm: 
      values: |
        controller:
          config:
            http-snippet: "proxy_cache_path /tmp/nginx-cache-ghost levels=1:2 keys_zone=ghost:2m use_temp_path=off max_size=1g inactive=24h;"
  destination:
    server: {{ .Values.spec.destination.server }} 
    namespace: infrastructure
  syncPolicy:
    automated:
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true