apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: privatebin 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: applications
  source:
    repoURL: {{ .Values.spec.repo }}
    targetRevision: master
    path: privatebin
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: privatebin
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
