apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: infrastructure
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 52.1.0
    helm:
      values: |
        namespaceOverride: infrastructure
        alertManager:
          enabled: false
        nodeExporter:
          enabled: false
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
            requests:
              memory: 75Mi
              cpu: 25m
        grafana:
          enabled: false
          adminPassword: "Yk9Pdnpkc3hTOG0xa014WFdRaVZVQmlqcEtFYjFOQTkK"
          sidecar:                              
            dashboards:
              enabled: true
              label: grafana_dashboard
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              kubernetes.io/tls-acme: "true" 
              kubernetes.io/ingress.class: "nginx"
            hosts:
              - grafana.devoops.one
            tls:
              - hosts:
                - grafana.devoops.one
                secretName: grafana-tls
        nodeExporter:
          enabled: false
        prometheusOperator:
          enabled: false
        prometheus:
          enabled: false
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  resources:
                    requests:
                      storage: 2Gi
            resources:
              requests:
                cpu: 50m
                memory: 300Mi
              limits:
                cpu: 300m
                memory: 500Mi
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
