apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: infrastructure
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 39.6.0
    helm:
      values: |
        namespaceOverride: infrastructure
        alertManager:
            enabled: false
        nodeExporter:
            resources:
                limits:
                    memory: 100Mi
                    cpu: 100m
                requests:
                    memory: 75Mi
                    cpu: 25m
        grafana:
            persistence:
                enabled: false
                #type: statefulset
                #size: 5Gi
            sidecar:                              
                dashboards:
                    enabled: true
                    label: grafana_dashboard
                prometheus:
        prometheusSpec:
            storageSpec: {}
                # volumeClaimTemplate:
                #    spec:
                #         resources:
                #             requests:
                #                 storage: 5Gi
            persistentVolume:
                enabled: false
            resources:
                limits:
                    memory: 250Mi
                    cpu: 100m
                requests:
                    memory: 100Mi
                    cpu: 50m
            ingress:
                enabled: true
                ingressClassName: ngin
                annotations:
                    cert-manager.io/cluster-issuer: "letsencrypt-stage"
                    kubernetes.io/tls-acme: "true" 
                    hosts:
                        - prometheus.512.ch
                    tls:
                        - hosts:
                            - prometheus.512.ch
                            secretName: prometheus-tls
  syncPolicy:
    #automated:
    #  prune: true
    #  selfHeal: true
    syncOptions:
      - CreateNamespace=true