apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: infrastructure
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 39.6.0
    helm:
      values: |
        namespaceOverride: infrastructure
        alertManager:
          enabled: false
        nodeExporter:
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
            requests:
              memory: 75Mi
              cpu: 25m
        grafana:
          sidecar:                              
            dashboards:
              enabled: true
              label: grafana_dashboard
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-stage"
              kubernetes.io/tls-acme: "true" 
              kubernetes.io/ingress.class: "nginx"
            hosts:
              - grafana.512.ch
            tls:
              - hosts:
                - grafana.512.ch
                secretName: grafana-tls
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  resources:
                    requests:
                      storage: 2Gi
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                cpu: 100m
                memory: 250Mi
  syncPolicy:
    syncOptions:
      - CreateNamespace=true