apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: infrastructure
  source:
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: 2.13.1
    chart: sealed-secrets 
  destination:
    server: {{ .Values.spec.destination.server }} 
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true 
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
