apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-generator 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: 'https://helm.mittwald.de'
    targetRevision: 3.4.0
    chart: kubernetes-secret-generator
  destination:
    server: {{ .Values.spec.destination.server }} 
    namespace: secret-generator
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
