apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sus-proxy 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: applications
  source:
    repoURL: {{ .Values.spec.repo }}
    targetRevision: feature/sus-proxy 
    path: süs-proxy
    helm:
      values: |
        domain: bin.{{ .Values.spec.domain }}
        cert_issuer: letsencrypt-stage
        namespace: sus-proxy
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: sus-proxy
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
