apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: applications
  source:
    repoURL: {{ .Values.spec.repo }}
    targetRevision: master 
    path: vikunja
    helm:
      values: |
        domain: do.{{ .Values.spec.domain }}
        cert_issuer: letsencrypt-prod
        namespace: vikunja
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: vikunja
  syncPolicy:
    automated:
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
