apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-stage
spec:
  acme:
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    email: "till@meyerzuwestram.net"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
