uptime:
  ingress:
    cert_issuer: letsencrypt-stage
    domain: up
  resources:
    limits:
      memory: 150Mi
      cpu: 200m
    requests:
      memory: 100Mi
      cpu: 50m
  storage:
    className: linode-block-storage-retain
    size: 5Gi
