argo-cd:
  server:
    config:
      url: https://argo.512.ch
    resources:
      limits:
        cpu: 250m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 250Mi
    additionalApplications:
    - name: 512.ch 
      namespace: argocd 
      project: default 
      source:
        repoURL: 'https://github.com/tillmzw/argocd.git'
        path: apps
        targetRevision: master
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          selfHeal: false 
  controller:
    resources:
      limits:
        cpu: 250m
        memory: 400Mi
      requests:
        cpu: 50m
        memory: 250Mi