apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:5.5.0-alpine
          ports:
            - containerPort: 2368
          env:
            - name: url
              value: "https://www.wir-feiern-mit-eu.ch"
            - name: database__client
              value: "mysql"
            - name: database__connection__host
              value: "mariadb"
            - name: database__connection__user
              value: "ghost"
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: mariadb-password
                  key: password
            - name: database__connection__database
              value: "ghost"
            - name: mail__transport
              value: "smtp"
            - name: mail__options__service
              value: "Mailgun"
            - name: mail__auth__user
              valueFrom:
                  secretKeyRef:
                    name: smtp-credentials
                    key: username
            - name: mail__auth__password
              valueFrom:
                  secretKeyRef:
                    name: smtp-credentials
                    key: password
            - name: mail_from
              valueFrom:
                secretKeyRef:
                      name: smtp-credentials
                      key: mailfrom
          volumeMounts:
          - name: ghost-data
            mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-data
        persistentVolumeClaim:
          claimName: ghost
