apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:5.4.1-alpine
          ports:
            - containerPort: 2368
          env:
            - name: url
              value: "https://www.wir-feiern-mit-eu.ch"
            - name: database__client
              value: "mysql"
            - name: database__connection__host
              value: "mariadb"
            - name: database__connection__user
              value: "ghost"
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: mariadb-password
                  key: password
            - name: database__connection__database
              value: "ghost"
          volumeMounts:
          - name: ghost-data
            mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-data
        persistentVolumeClaim:
          claimName: ghost
