apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:5.2.3-alpine
          ports:
            - containerPort: 2368
          env:
            - name: url
              value: "https://ghost.512.ch"
            - name: database__client
              value: "mysql"
            - name: database__connection__host
              value: "mariadb"
            - name: database__connection__user
              value: "ghost"
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: mariadb-password
                  key: password
            - name: database__connection__database
              value: "ghost"
          volumeMounts:
          - name: ghost-data
            mountPath: /var/lib/ghost/content
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
      volumes:
      - name: ghost-data
        persistentVolumeClaim:
          claimName: ghost
