apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost-ingress
  namespace: ghost
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/server-alias: "www.wir-feiern-mit-eu.ch"
spec:
  tls:
    - hosts:
        - ghost.512.ch
        - www.wir-feiern-mit-eu.ch
      secretName: ghost-tls
    - host: ghost.512.ch
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: ghost
              port:
                number: 80
