apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-password
  namespace: ghost
spec:
  encryptedData:
    password: AgBMNz+j3/Uc4vJ4h9kx1FSk7wHyEVKyA8wPrH8FbvKNyljMEHixiHtPhKk6cx96QHqzHJHwSbcIN0sKjbZxpJVNBjLDFre54ySYEW7wxgIKZSbO93qLo18u4C9T8VEKRTcVsqfUTFH4X1/DuaShI15Jx6d8r4EWKI7IRnyIV8r3ABYhPYukjEt5FeCmbo2uAGTSXiREr4Zcberi4rhhdw0QcaYdEdcriervn1bI8r4hWJY5QKYK6+E0xg5kc069hTnPJUzee+eirdedBvXVQ7DFXX04xSR94W3nYHdG5SER9Kdb5OTY3BOJ97reaQ+/1bgs9+OcUKWcWxZ1nuIDNRUSI6K7L4BOKKIFZ4Q9xpXRuO6wF5Lf+g2olYE2pLpUD7oGMYPCDGipvzpEoc5smsCxn9cykrQ22duoxc68psnPFKVplzYG1VE88z5wJUUWXljBNQVPgGikTOzqKOttAipVLsxNjtmZSr93pqHESQH3UVVmKxBp4VMuv4YFapSGvzQIea1B4nun2KFMfbaWqjhxETmQDHa9nj1OaJZkURWnz3ppsyruJp8Vylt6K80zPtQvV2Cx9NEAQivlkywHV9sDTzSOZPcxV/0U+1MKs1+DjXMgh1SB3Lk8qV+ril3qtLXPtBF7uvWvAC0gnOLUdDXh92lCpO3dxjlQN/7/LCQe2LhC346ckxKJUce5ktSLk88EYr3Bicw/gPVlvgNSMbZwN2rUcIVceRsZN6HUh+WXxKlfvbA5PMkzv5O9pQs=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mariadb-password
      namespace: ghost
    type: Opaque

