apiVersion: v1
kind: Secret
metadata:
  name: mariadb-password
  annotations:
    secret-generator.v1.mittwald.de/type: string
    secret-generator.v1.mittwald.de/secure: "yes"
    secret-generator.v1.mittwald.de/autogenerate: password
type: Opaque
data:
  username: ghost
