ghost:
  ingress:
    cert_issuer: letsencrypt-stage
    domain: ghost
    proto: https
  storage:
    className: linode-block-storage-retain
    size: 5Gi
  replicas: 1
  resources:
    limits:
      memory: 750Mi
      cpu: 400m
    requests:
      memory: 500Mi
      cpu: 200m
database:
  storage:
    className: linode-block-storage-retain
    size: 5Gi
  resources:
    limits:
      memory: 400Mi
      cpu: 400m
    requests:
      memory: 400Mi
      cpu: 100m