apiVersion: v1
kind: ConfigMap
metadata:
  name: photoprism-config
  namespace: {{ .Values.namespace }}
data:
  PHOTOPRISM_AUTH_MODE: password
  PHOTOPRISM_SITE_CAPTION: "R & T's Hochzeit"
  PHOTOPRISM_SITE_DESCRIPTION: 'Wir feierten mit euch und hier sind die Fotos'
  PHOTOPRISM_SITE_URL: 'https://fotos.wir-feiern-mit-eu.ch/'
  PHOTOPRISM_DISABLE_RESTART: "true"
  PHOTOPRISM_DISABLE_PLACES: "true"
  PHOTOPRISM_DISABLE_CLASSIFICATION: "true"
  PHOTOPRISM_DISABLE_SIPS: "true"
  PHOTOPRISM_DISABLE_EXIFTOOL: "true"
  PHOTOPRISM_DISABLE_DARKTABLE: "true"
  PHOTOPRISM_DISABLE_RAWTHERAPEE: "true"
  PHOTOPRISM_DISABLE_IMAGEMAGICK: "true"
  PHOTOPRISM_DISABLE_HEIFCONVERT: "true"
  PHOTOPRISM_DISABLE_RSVGCONVERT: "true"
  PHOTOPRISM_DISABLE_VECTORS: "true"
  PHOTOPRISM_DISABLE_RAW: "true"