apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vikunja-smtp-password
  namespace: vikunja
spec:
  encryptedData:
    password: AgBO2L4hfeoZ4L3BMor4/+SAD6Q82o4nhybNPoIPHFsMr/wj+7RKTFKv7WCxmWHchuiOkdZUTB59JmTUX+zg8MA8mTvxSw5rga3S4ecqnuyqNgnEYB4ous4IQqugAC+JH+IyXZzC4WpQ0HwEuZ3mBBuRgZLKMt706PAyhXk4ABziWmn2SQqct0FJ/7gb0AzjnunRbwZU02H5P4r+FdSGBLX8l39Doo60TeySKWhCQaG2JhjXSTklEEVOjwFyH2yR783L/oB6x7/7WCvnomy+BZ1SBZ8ABgGbOrN2tjlrvXwJC+Oh4GwEOP3MxnSaMfq5pNIKuz+xPB3Jhhs6RbGqq+ufTp99+57S85SQE3rlCfSEInb0j3a6XewgYqezzVuD+P+P772QU0dZJk38Ou54gbfAqTb+wsEwVUTse8hZBW8xVzo3MqSlDw40SLV37ZUd61i00ZIayVr/jzzvaFVu7xYfFS98ChwaQQaUz/ilO28kvH5wlJttEYWR66RtDnoWXJ+XDH6w8kBlhy9fv5xKOupQTvUyd4LlQTcvamCCXfBPYdltUAePpTt0IaPWd8AipJcOYF7Nsx3UYAxnA/JX3zUvoCCsjU2HreUpksGwxylOCZTVZ0X73apaojKBfCe3PPm6fhAV574tbHN6s4wA+SFID3kQjvjZ0tpzgk8ZprAQ4prEPrQpDTT/tB2PZVPzqgeKUrVyTlZLgCwcmSYeNFobM8VFfjYigmH62h99/nEfpMiwYAZHZWT09E7YubhmHqSu+Q==
    username: AgBNBI5fREQJxvAV0IXRebykZx+wFpAUdGYC5QR5wNdyE7olq65C5myLPcjphA1ubEEA5bKamYssx3VesPGimOb0+J5M+naWWFCFsRUSzlZTPM+qdNrs7WyOLvTEjAz/TaeIfB2Ii6ER4aye6wDZeQuWgC+kVitgp6MVfAyiFE9wKCWJ39TmNgQqMeGUF7MXhWvS/k+5zp/5hgWnIbLXJRyMgM2o+wtIJZ1gStZZB5B2ShQyTzwViy1n2Ejeu3E8QCnTva5nYo8lpH23AXEUX9QQFw3sFCWGfVvi2fa0ZIeYPRJ1quFS4sC1nxVygBc4xG37C0wBNCC7fr6AbWYvd9LT9gkRPUOeKLYsszPMFZ1de1aIgdObrDhahDQLxi4VyXvr1CotcmqoVA5m3nLI3AYV/cERmMAmYzLWf/mNHRJ4YuVVIsItBlNDiQ/IJAxtmaAXeJ0lNEjYwvq9IjMjvnJkWva9TpHsiyi7Vr5iVtdTIgSrZ0N9TON8reaSrKZsiijRnlrzCMB12taipZ3jIezONQEJsMXh3MhmL20+WaLEMuEn6ibSMuOSY3H1WisNyPKrTK+aj8Zo/HpZ68aGuzyV4PUJgML6qo9i9rraK1+PHR0DjAcGSOjMBnOeD9p9s0djOIYJYC27kPMSXfEtRYT0EhJFO98k9D5VMJictdMIB/OwOaSIz38y6lTVgUlFZTH1+K8q7sSl0Tfvo3mxRGl0ZKbD
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: vikunja-smtp-password
      namespace: vikunja
    type: Opaque

